[tool.poetry]
name = "vrtool"
version = "0.0.1"
description = ""
authors = ["Wouter Jan Klerk <wouterjan.klerk@deltares.nl>"]
maintainers = [
  "Carles S. Soriano Pérez <carles.sorianoperez@deltares.nl>",
  "Dennis Tang <dennis.tang@deltares.nl>",
  "Edwin Speen <edwin.spee@delatres.nl>",
  "Stephan Rikkert <stephan.rikkert@deltares.nl>",
]
readme = "README.md"
repository = "https://github.com/Deltares/veiligheidsrendement"
packages = [{include="vrtool"},]
keywords = ["civil-engineering", "dikes", "flood-defence", "deltares"]
classifiers = [
  'Intended Audience :: Developers, Civil Engineers',
  'License :: OSI Approved :: GNU General Public License v3 (GPLv3)',
  'Natural Language :: English',
  'Programming Language :: Python :: 3',
  'Topic :: Civil Engineering :: Dike reinforcements'
]

[tool.poetry.dependencies]
python = "^3.9, <3.11"
numpy = "^1.24.2"
matplotlib = "^3.7.0"
pandas = "^1.5.3"
shapely = "^2.0.1"
scipy = "1.8.1"
seaborn = "^0.12.2"
openturns = "1.19"
openpyxl = "^3.1.1"

[tool.poetry.dev-dependencies]
pytest = "^7.2.1"
pytest-cov = "^3.0.0"
black = "^22.8.0"
isort = "^5.10.1"
coverage = "^6.4.4"
teamcity-messages = "^1.32"

[tool.black]
line-length = 88
target-version = ['py310']
exclude = '''
(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | \.virtualenvs
  )/
)
'''

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
]

[tool.commitizen]
name = "cz_conventional_commits"
version = "0.0.1"
tag_format = "v$major.$minor.$patch"
version_files= [
    "src/__init__.py",
    "pyproject.toml:version",]