name: Documentation Improvement
description: Report wrong or missing documentation
labels: [documentation, "triage required"]
type: task
projects: ["Deltares/105"]

body:
  - type: checkboxes
    attributes:
      label: VRTool Suite version checks
      options:
        - label: I have checked that the issue still exists on the latest version of the docs in `main` [here](https://github.com/Deltares/Veiligheidsrendement/docs).
          required: true
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: To which components of the VRTool Suite does it relate to?
      multiple: true
      options:
        - Core
        - Preprocessor
        - Dashboard
        - Documentation
        - Unclear
    validations:
      required: true
  - type: dropdown
    id: kind
    attributes:
      description: What kind of documentation issue is this?
      label: Kind of issue
      options:
        - Documentation is wrong
        - Documentation is unclear
        - Documentation is missing
    validations:
      required: true
  - type: textarea
    id: location
    attributes:
      description: >
        If the docs are wrong or unclear please provide the URL of the documentation in question.
      label: Location of the documentation
  - type: textarea
    id: problem
    attributes:
      description: >
        Please provide a description of the documentation problem.
      label: Documentation problem
    validations:
      required: true
  - type: textarea
    id: suggested-fix
    attributes:
      description: >
        Please explain your suggested fix and why it's better than the existing documentation.
      label: Suggested fix for documentation
