name: vrtool_env
channels:
  - conda-forge
  - nodefaults
dependencies:
  - conda-forge::python=3.13
  - conda-forge::poetry
  - conda-forge::openturns
  # If this does not work, try adding in pyproject.toml the following PINNED dependency:
  # urllib3 = "1.26.15"