name: vrtool_env
channels:
  - conda-forge
  - nodefaults
dependencies:
  - conda-forge::python=3.10
  - conda-forge::poetry=1.3.2
  - conda-forge::openturns
  # If this does not work, try adding in pyproject.toml the following PINNED dependency:
  # urllib3 = "1.26.15"