# Exclusive configuration for TeamCity, poetry is already installed there.
name: vrtool_env
channels:
  - conda-forge
  - nodefaults
dependencies:
  - conda-forge::python=3.10
  - conda-forge::openturns=1.19
